server:
  port: 9010

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /console

  ## Hibernate Properties
  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
    showSql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  mail:
     host: smtp.gmail.com
     port: 587
     username: uprism.user001@gmail.com
     password: uprism@123
     properties:
       mail:
         smtp:
           auth: true
           starttls.enable: true
